<?php
/**
 * Knowledge Base (Wiki) UI
 * 
 * Variables available:
 * - $wikiIndex: ['Category' => ['slug' => ['title', 'path', ...]]]
 * - $pageData: ['title', 'html', 'slug']
 * - $activeCategory: string
 */

// Generate TOC from H2 tags
$toc = [];
if (!empty($pageData['html'])) {
    preg_match_all('/<h2.*?id="(.*?)".*?>(.*?)<\/h2>/', $pageData['html'], $matches, PREG_SET_ORDER);
    foreach ($matches as $match) {
        $toc[] = [
            'id' => $match[1],
            'title' => strip_tags($match[2])
        ];
    }
}
?>

<div class="h-[calc(100vh-80px)] overflow-hidden flex flex-col md:flex-row -m-6">
    
    <!-- Sidebar: Navigation -->
    <div class="w-full md:w-80 bg-white border-r border-gray-200 flex flex-col h-full">
        <!-- Search -->
        <div class="p-4 border-b border-gray-100">
            <div class="relative">
                <span class="material-symbols-outlined absolute left-3 top-2.5 text-gray-400 text-[20px]">search</span>
                <input type="text" id="wiki-search" placeholder="Search docs..." 
                       class="w-full pl-10 pr-4 py-2 bg-gray-50 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-indigo-500 focus:bg-white transition-all">
            </div>
        </div>
        
        <!-- Link List -->
        <div class="flex-1 overflow-y-auto overflow-x-hidden p-4 space-y-6" id="wiki-nav">
            <?php foreach ($wikiIndex as $category => $pages): ?>
                <div class="wiki-category">
                    <h3 class="text-xs font-bold text-gray-400 uppercase tracking-wider mb-2 px-2 flex items-center gap-2">
                        <span class="material-symbols-outlined text-[16px]">folder_open</span>
                        <?= htmlspecialchars($category) ?>
                    </h3>
                    <ul class="space-y-0.5">
                        <?php foreach ($pages as $slug => $page): ?>
                            <?php $isActive = ($pageData['slug'] === $slug); ?>
                            <li>
                                <a href="?doc=<?= $slug ?>" 
                                   class="block px-3 py-2 text-sm rounded-lg transition-colors flex items-center gap-2 wiki-link
                                          <?= $isActive ? 'bg-indigo-50 text-indigo-700 font-medium' : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900' ?>">
                                    <?php if ($isActive): ?>
                                        <span class="w-1.5 h-1.5 rounded-full bg-indigo-500"></span>
                                    <?php endif; ?>
                                    <span class="truncate"><?= htmlspecialchars($page['title']) ?></span>
                                </a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endforeach; ?>
            
            <div id="no-results" class="hidden text-center py-8 text-gray-400 text-sm">
                No matching docs found.
            </div>
        </div>
        
        <!-- Footer -->
        <div class="p-4 border-t border-gray-100 bg-gray-50 text-xs text-center text-gray-400">
            Generated by Wiki Addon • Markdown Support
        </div>
    </div>
    
    <!-- Main Content -->
    <div class="flex-1 flex overflow-hidden min-w-0 bg-white relative">
        <!-- Scrollable Article Area -->
        <div class="flex-1 overflow-y-auto px-8 py-10 md:px-12 lg:px-16 scroll-smooth z-0" id="wiki-scroll-container">
            <div class="max-w-3xl mx-auto pb-20">
                <!-- Breadcrumb -->
                <nav class="flex items-center gap-2 text-xs font-medium text-gray-500 mb-8 uppercase tracking-wide">
                    <span class="text-gray-400">Knowledge Base</span>
                    <span class="text-gray-300">/</span>
                    <span class="text-indigo-600"><?= htmlspecialchars($activeCategory ?? 'Docs') ?></span>
                </nav>
                
                <!-- Page Title -->
                <h1 class="text-4xl md:text-5xl font-extrabold text-slate-900 tracking-tight mb-8 leading-tight">
                    <?= htmlspecialchars($pageData['title']) ?>
                </h1>
                
                <!-- Markdown Content -->
                <article class="prose prose-slate prose-lg max-w-none 
                                prose-headings:font-bold prose-headings:text-slate-900 prose-headings:scroll-mt-24
                                prose-a:text-indigo-600 prose-a:no-underline hover:prose-a:underline
                                prose-img:rounded-xl prose-img:shadow-lg prose-img:border prose-img:border-gray-100
                                prose-code:text-pink-600 prose-code:bg-pink-50 prose-code:font-normal prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded">
                    <?= $pageData['html'] ?>
                </article>
                
                <!-- Feedback / Footer -->
                <div class="mt-20 pt-8 border-t border-gray-100 flex items-center justify-between text-sm text-gray-400">
                    <div class="flex items-center gap-2">
                         <span class="material-symbols-outlined text-[18px]">edit_document</span>
                         <span>Source: <?= basename($pageData['path'] ?? 'unknown.md') ?></span>
                    </div>
                    <div>
                        Last updated: <?= date('F j, Y', filemtime($pageData['path'] ?? __FILE__)) ?>
                    </div>
                </div>
            </div>
        </div>
        
        <!-- Right Sidebar: On This Page (Desktop Only) -->
        <?php if (!empty($toc)): ?>
        <div class="hidden xl:block w-72 border-l border-gray-100 bg-white p-8 overflow-y-auto z-10">
            <div class="sticky top-0">
                <h4 class="text-xs font-bold text-gray-400 uppercase tracking-widest mb-6">On this page</h4>
                <ul class="space-y-4 text-sm relative border-l border-gray-100 ml-1">
                    <?php foreach ($toc as $item): ?>
                    <li class="pl-4 -ml-px border-l-2 border-transparent hover:border-indigo-500 transition-colors">
                        <a href="#<?= htmlspecialchars($item['id']) ?>" 
                           class="block text-gray-500 hover:text-indigo-600 transition-colors leading-snug">
                            <?= $item['title'] ?>
                        </a>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>

<script>
// Keyboard Shortcut for Search
document.addEventListener('keydown', (e) => {
    if (e.key === '/' && document.activeElement.tagName !== 'INPUT' && document.activeElement.tagName !== 'TEXTAREA') {
        e.preventDefault();
        document.getElementById('wiki-search').focus();
    }
});

// Client-side Search
document.getElementById('wiki-search').addEventListener('input', function(e) {
    const term = e.target.value.toLowerCase();
    const links = document.querySelectorAll('.wiki-link');
    let hasResults = false;
    
    links.forEach(link => {
        const text = link.textContent.toLowerCase();
        const li = link.parentElement;
        const category = li.closest('.wiki-category');
        
        if (text.includes(term)) {
            li.style.display = 'block';
            hasResults = true;
            if (category) category.style.display = 'block';
        } else {
            li.style.display = 'none';
        }
    });

    document.querySelectorAll('.wiki-category').forEach(cat => {
        if (term === '') {
            cat.style.display = 'block';
            cat.querySelectorAll('li').forEach(li => li.style.display = 'block');
        } else {
            const hasVisibleChildren = Array.from(cat.querySelectorAll('li')).some(li => li.style.display !== 'none');
            cat.style.display = hasVisibleChildren ? 'block' : 'none';
        }
    });
    
    const noRes = document.getElementById('no-results');
    noRes.classList.toggle('hidden', hasResults || term === '');
    if (!hasResults && term !== '') {
        noRes.innerHTML = `<span class="block mb-2 text-2xl">🤷‍♂️</span>No docs found for "<span class="font-bold text-gray-900">${e.target.value}</span>"`;
    }
});
</script>
